import Link from "next/link";
import {
  TrendingUp, ArrowRight, BarChart3,
  PieChart, LineChart, BrainCircuit,
  Target, Lightbulb, Sparkles,
} from "lucide-react";

const insights = [
  { icon: <BarChart3 className="w-5 h-5 text-blue-400" />, title: "Income vs Expense Trends", desc: "See your income and expense patterns over 6 months with beautiful interactive bar charts." },
  { icon: <PieChart className="w-5 h-5 text-purple-400" />, title: "Category Breakdown", desc: "Visualize exactly where your money goes with a color-coded pie chart by spending category." },
  { icon: <LineChart className="w-5 h-5 text-cyan-400" />, title: "Savings Trend", desc: "Track your monthly savings over time and see if you're improving month over month." },
  { icon: <BrainCircuit className="w-5 h-5 text-green-400" />, title: "AI Financial Tips", desc: "Personalized tips generated by Gemini AI based on your actual spending data." },
  { icon: <Target className="w-5 h-5 text-orange-400" />, title: "Savings Rate Tracker", desc: "Know your exact savings rate and get tips to push it above the recommended 20%." },
  { icon: <Lightbulb className="w-5 h-5 text-yellow-400" />, title: "Smart Recommendations", desc: "AI detects patterns in your spending and gives actionable recommendations weekly." },
];

export default function AboutInsightsPage() {
  return (
    <main className="min-h-screen bg-[#070d1f] text-white">
      <nav className="flex items-center justify-between px-8 py-5 border-b border-white/5 backdrop-blur-md sticky top-0 z-50 bg-[#070d1f]/80">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center">
            <TrendingUp className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-lg tracking-tight">FinSight AI</span>
        </Link>
        <div className="hidden md:flex items-center gap-8 text-sm text-white/60">
          <Link href="/features" className="hover:text-white transition-colors">Features</Link>
          <Link href="/about-insights" className="text-white">Insights</Link>
          <Link href="/pricing" className="hover:text-white transition-colors">Pricing</Link>
          <Link href="/docs" className="hover:text-white transition-colors">Docs</Link>
        </div>
        <Link href="/sign-up" className="px-4 py-2 rounded-lg bg-white text-[#070d1f] text-sm font-semibold hover:bg-white/90">
          Get started free
        </Link>
      </nav>

      <section className="px-8 pt-20 pb-12 text-center max-w-4xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-400 text-xs font-medium mb-6">
          <Sparkles className="w-3 h-3" />
          AI-Powered Analytics
        </div>
        <h1 className="text-5xl font-bold mb-6 leading-tight">
          Understand your money{" "}
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
            like never before
          </span>
        </h1>
        <p className="text-white/50 text-lg max-w-2xl mx-auto">
          FinSight AI turns your raw transaction data into beautiful visualizations and actionable insights powered by Gemini AI.
        </p>
      </section>

      <section className="px-8 py-8 border-y border-white/5 mb-16">
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
          {[
            { value: "6 months", label: "of historical data" },
            { value: "Real-time", label: "data updates" },
            { value: "AI-powered", label: "personalized tips" },
            { value: "10+", label: "chart types" },
          ].map((s, i) => (
            <div key={i}>
              <div className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-cyan-400 mb-1">{s.value}</div>
              <div className="text-white/40 text-sm">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="px-8 pb-16 max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {insights.map((item, i) => (
            <div key={i} className="rounded-2xl border border-white/5 bg-white/3 p-6 hover:border-white/10 transition-all">
              <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center mb-4">{item.icon}</div>
              <h3 className="font-semibold mb-2">{item.title}</h3>
              <p className="text-white/40 text-sm leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="px-8 py-16 max-w-4xl mx-auto">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-8 text-center">
          <BrainCircuit className="w-12 h-12 text-blue-400 mx-auto mb-4" />
          <h2 className="text-2xl font-bold mb-3">Your personal financial analyst</h2>
          <p className="text-white/40 mb-6 max-w-xl mx-auto">
            FinSight AI analyzes your spending patterns and delivers personalized reports every month.
          </p>
          <Link href="/sign-up" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-blue-500 to-cyan-500 text-white font-semibold hover:opacity-90 transition-all">
            See your insights <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      <footer className="px-8 py-8 border-t border-white/5 text-center text-white/20 text-sm">
        © 2026 FinSight AI. Built with Next.js, Gemini & ❤️
      </footer>
    </main>
  );
}
